spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  secretKey: yanabadaSecretKeyyanabadaSecretKeyyanabadaSecretKey

email:
  host: smtp.gmail.com
  port: 587
  user: tjdtn0219@ajou.ac.kr
  password: wvuh cnxb oizl gnjv

chatroom:
  topic:
    prefix: "/sub/chatroom/"
